on: push

name: Github issue create

jobs:
  check_modified_files:
    name: Check modified files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check modified files
        id: check_files
        run: |
          echo "== ðŸ” List of all changed files: =="
          git diff --name-only HEAD^ HEAD

          echo "== âš™ï¸ List of only 'database' changed files: =="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file = database/* ]]; then
              echo "This modified file is under the 'database' folder."
              echo "::set-output name=run_job::true"
              break
            else
              echo "::set-output name=run_job::false"
            fi
          done < files.txt

  create_analytic_issue:
    name: Create analytics issue
    runs-on: ubuntu-latest

    needs: check_modified_files
    if: needs.check_modified_files.outputs.run_job == 'true'

    permissions:
      issues: write
    steps:
      - name: Create issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "${{ github.event.pusher.name }}"
          labels: "analytics, chore"
          title: "Try create issue using github actions"
          body: |
            ## Try create using github actions

            follow me
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
